### ISSUE TITLE
Update landing with chain logos

### ISSUE THREAD

**Issue by roman-monk** [beefyfinance/beefy-landing#4]
1) Move social icons to the top-right
2) Add Chain icons with current hover animations

![fix](https://user-images.githubusercontent.com/71946691/116381001-139af980-a847-11eb-8b6c-2932173fc278.png)

Icons: [wetransfer-72e221.zip](https://github.com/beefyfinance/beefy-landing/files/6390683/wetransfer-72e221.zip)

**Comment by andynullwong** [comment]
Hello I'll pick this one up
